package com.open.spring.mvc.capstone;

import java.util.ArrayList;
import java.util.List;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.open.spring.mvc.person.Person;

import jakarta.persistence.CascadeType;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.JoinTable;
import jakarta.persistence.ManyToMany;
import jakarta.persistence.Table;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * A capstone project, mirrored from the Jekyll capstone posts.
 *
 * The posts under pages/_posts/capstone are the source of truth for which projects
 * exist and what they are called; this table exists so a mentor can be attached to
 * one. `slug` is the shared identity -- it is the capstone post's permalink segment
 * (/capstone/<slug>/), so a row here always points at a real page.
 *
 * Rows are kept in step by scripts/sync_capstones.py, which reads
 * /capstone/projects.json (generated by Jekyll from those same posts) and upserts
 * by slug. Nothing here is hand-maintained.
 */
@Entity
@Table(name = "capstone_project")
@Data
@NoArgsConstructor
public class CapstoneProject {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;

    /** Permalink segment of the capstone post, e.g. "hawkhub". Stable identity. */
    @Column(unique = true, nullable = false)
    private String slug;

    private String title;

    @Column(columnDefinition = "text")
    private String description;

    /** Site-relative path to the project's page, e.g. "/capstone/hawkhub/". */
    private String url;

    @ManyToMany(fetch = FetchType.LAZY, cascade = {CascadeType.PERSIST, CascadeType.MERGE})
    @JoinTable(
        name = "capstone_mentors",
        joinColumns = @JoinColumn(name = "capstone_id"),
        inverseJoinColumns = @JoinColumn(name = "person_id")
    )
    @JsonIgnore
    private List<Person> mentors = new ArrayList<>();

    public CapstoneProject(String slug, String title, String description, String url) {
        this.slug = slug;
        this.title = title;
        this.description = description;
        this.url = url;
    }

    public void addMentor(Person person) {
        if (!this.mentors.contains(person)) {
            this.mentors.add(person);
        }
    }

    public void removeMentor(Person person) {
        this.mentors.remove(person);
    }
}
